Финальная работа второго спринта.
Giftig84/burger pull request #4
Opened 2023-02-23 23:34 UTC by Giftig84

Проект. Перенос состояния в Redux. Изменение порядка ингредиентов с React DND

2023-02-24 04:41 UTC, andryxxa93 requested changes
Здравствуйте! Проделана огромная работа!
Что понравилось:
- Используется `useMemo` и `useCallback`
- Реализован скролл по категориям
- Хорошо настроен `Dnd`

Что необходимо исправить:
- Для каждого экшена, который связан с запросом к API долден быть создан усилитель. Для таких экшенов необходимо описать типы `_REQUEST , _SUCCESS , _ERROR` .
- Разделите `constructorReducer.js` на несколько. (подробнее см. комментарий в pull-request).
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-24 04:41 UTC, andryxxa93 commented on src/components/App/App.js
> +    const isLoading = useSelector(state => state.api.isLoading);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-02-24 04:41 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +export  default BurgerIngredients ;
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-02-24 04:41 UTC, andryxxa93 commented on src/services/reducers/constructorReducer.js
> +export const constructorReducer= (state = defaultState, action) => {
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-02-25 07:22 UTC, Giftig84 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +export  default BurgerIngredients ;
Ваши замечания исправлены, добавил React.memo на два компонента, которые зависят от пропса.

2023-02-25 07:22 UTC, Giftig84 commented on src/services/reducers/constructorReducer.js
> +export const constructorReducer= (state = defaultState, action) => {
Сделано, ваши замечания исправлены.

2023-02-25 18:32 UTC, andryxxa93 requested changes
**Необходимо исправить**
- Необходимо добавить усилители для запроса на получение номера заказа. Сейчас у вас есть только `ORDER_REQUEST `.
- Так же eсли при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

2023-02-25 19:37 UTC, Giftig84 commented
> 



> **Необходимо исправить**
> 
> * Необходимо добавить усилители для запроса на получение номера заказа. Сейчас у вас есть только `ORDER_REQUEST `.
> * Так же eсли при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Не очень понятно, что требуется. Я все это сделал: 
![image](https://user-images.githubusercontent.com/15526828/221376226-9d86d212-d137-42d2-bde7-4b84bf737ec0.png)
Т.е. в apiActions.js в зависимости от типа, вызывается либо получение номера заказа, либо ингредиентов. В catch приводим к первоначальному состоянию.

2023-02-26 15:46 UTC, andryxxa93 commented
У вас в `isLoadingSelector` - ошибка. Вы обращаетесь к части стора `api` которого нет. Поправьте и ваша работа будет принята!

**Можно лучше**
- Когда конструктор пуст лучше дизейблить или скрывать кнопку "Оформить заказ" иначе будет уходить запрос с пустым массивом и вызывать ошибку.

2023-02-26 15:57 UTC, Giftig84 commented
> У вас в `isLoadingSelector` - ошибка. Вы обращаетесь к части стора `api` которого нет. Поправьте и ваша работа будет принята!
> 
> **Можно лучше**
> 
> * Когда конструктор пуст лучше дизейблить или скрывать кнопку "Оформить заказ" иначе будет уходить запрос с пустым массивом и вызывать ошибку.

Ваши замечания исправлены.

2023-02-26 16:12 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-02-26 16:52 UTC, Giftig84 commented
> Супер, вы отлично поработали! Поздравляю! Работа принята. Желаю удачного продолжения обучения!

Спасибо!

2023-02-26 16:52 UTC, merged