Спринт 3 финальная работа
Giftig84/burger pull request #5
Opened 2023-03-11 18:22 UTC by Giftig84

2023-03-11 21:02 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
- Реализован механизм обновления токена
- Настроены все редиректы
- Есть защита роутов от не авторизованных пользователей

Что необходимо исправить:
- Невозможно изменить данные юзера - не появляются кнопки "Сохранить" и "Отмена".

<img width="812" alt="Снимок экрана 2023-03-11 в 23 38 57" src="https://user-images.githubusercontent.com/60173362/224510563-4da91aa3-eca6-41a1-b7ca-7fd7e94afd49.png">

- Вы реализовали механизм обновления токена - это отлично! Но следующий за ним повторный запрос всё равно падает из-за того, что в нём используется старый - протухший токен.

<img width="1440" alt="Снимок экрана 2023-03-11 в 23 41 17" src="https://user-images.githubusercontent.com/60173362/224510671-783be679-df01-41b3-8104-041dd743639e.png">

- Если перейти в профиль и обновить страницу, то перекидывает на главную страницу. 
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- Лого обычно делают ссылкой на главную страницу.
- Ссылка "Конструктор" не работает
- При переходе в личный кабинет неавторизованным пользователем происходит попытка получить данные юзера, запрос валится потому что токена нет, но потом начинается процесс обновления токена, который так же валится, потому что refresh токена тоже нет. Это лишние запросы, хорошо бы добавить проверку, что если в куках и localStorage нет токенов, то никаких запросов не делать.
- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.
<img width="635" alt="Снимок экрана 2023-03-11 в 23 46 43" src="https://user-images.githubusercontent.com/60173362/224510833-dd7fdd61-9602-4ef1-815a-c217988702e4.png">

- Роут `/reset-password` должен быть доступен только через `/forgot-password`
- Авторизованному юзеру не должны быть доступны роуты - `/login` `register` и `forgot-password`.
- У вас так организован код, что при заходе на главную страницу, даже если в куках есть токен, то авторизация не происходит, до тех пор, пока не попытаться перейти на страницу профиля. Хорошо бы при первом рендере приложения проверять если токен, и если есть, то попытаться им получить данные юзера.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-11 21:02 UTC, andryxxa93 commented on src/components/BurgerConstructor/FinishOrder/FinishOrder.js
> +        debugger;
**Необходимо исправить**
`debugger` необходимо удалять перед сдачей на проверку

2023-03-11 21:02 UTC, andryxxa93 commented on src/components/App/App.js
> +                    <Route path="/" element={<Main/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-11 21:02 UTC, andryxxa93 commented on src/pages/Login.js
> +    if (isAuth) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-13 22:29 UTC, Giftig84 commented on src/components/BurgerConstructor/FinishOrder/FinishOrder.js
> +        debugger;
Ваши замечания исправлены.

2023-03-13 22:29 UTC, Giftig84 commented on src/pages/Login.js
> +    if (isAuth) {
Спасибо, Ваши замечания исправлены.

2023-03-14 05:47 UTC, andryxxa93 commented
Супер! Вы отлично поработали, но осталось несколько небольших замечаний: 

- Данные юзера невозможно изменить, так как в теле запроса пусто, туда нужно вкладывать новые данные. Пожалуйста посмотрите ещё раз тех задание.

<img width="1440" alt="Снимок экрана 2023-03-14 в 08 38 58" src="https://user-images.githubusercontent.com/60173362/224906447-ca88eace-0bc3-43a9-9ca8-a2ace4a032ae.png">

- При попытке изменить данные юзера не работает обновление токена, хотя при получении данных работает. 

<img width="1439" alt="Снимок экрана 2023-03-14 в 08 42 24" src="https://user-images.githubusercontent.com/60173362/224906938-12ea9078-6156-42a1-b46e-bfaa8d198852.png">

2023-03-14 15:44 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-15 21:43 UTC, merged