sprint-4/step-1
Giftig84/burger pull request #6
Opened 2023-03-28 15:07 UTC by Giftig84

2023-03-28 15:51 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
Что понравилось:
- Типизировали хуки
- Практически не использовали `any`
- Не использовали `ts-ignore`

Что необходимо исправить:
- У вас остались не типизированы функции в файле `utils.js` 

В pull request вы так же найдете комментарии с рекомендациями как можно улучшить код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

2023-03-28 15:51 UTC, andryxxa93 commented on src/ImportFiles/endPointUrl.tsx
> +export const BASE_URL:"https://norma.nomoreparties.space/api" =  "https://norma.nomoreparties.space/api"
**Можно лучше**
Тут можно указать просто `string`

2023-03-28 15:51 UTC, andryxxa93 commented on src/components/App/App.tsx
> +    const accessToken: string | undefined = getCookie('token');
**Можно лучше**
Ключи токенов можно так же записывать в константы - так удобнее когда нужно использовать в разных местах проекта и исключает ошибку

2023-03-28 15:51 UTC, andryxxa93 commented on src/components/AppHeader/AppHeader.tsx
> +    const location = useLocation();
**Можно лучше**
Хук `useLocation` так же можно типизировать `useLocation<ILocation>()`

2023-03-28 15:51 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +    const totalSum: number = useMemo( (): number=>{
**Можно лучше**
`typescript` умеет подхватывать типы сам, поэтому не нужно так явно их везде указывать. 
Тут достаточно будет указать так -
`    const totalSum = useMemo<number>( () => {`

2023-03-28 21:26 UTC, Giftig84 commented on src/ImportFiles/endPointUrl.tsx
> +export const BASE_URL:"https://norma.nomoreparties.space/api" =  "https://norma.nomoreparties.space/api"
Ваше замечание исправлено.

2023-03-28 21:28 UTC, Giftig84 commented on src/components/AppHeader/AppHeader.tsx
> +    const location = useLocation();
Не смог реализовать такую конструкцию useLocation<ILocation>() выкидывает ошибку, TS 2558: Expected 0 type arguments, but got 1.

2023-03-28 21:28 UTC, Giftig84 commented on src/components/App/App.tsx
> +    const accessToken: string | undefined = getCookie('token');
Ваше замечание исправлено.

2023-03-28 21:28 UTC, Giftig84 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +    const totalSum: number = useMemo( (): number=>{
Ваше замечание исправлено.

2023-03-29 05:39 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-06 20:13 UTC, merged